FROM ubuntu
RUN apt-get update \
    && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*
CMD curl -sA "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Mobile Safari/537.36" https://ip.cn | awk -F "<code>" '/code/ {print $2}' | awk -F"<" '{print $1}'
